spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 200104
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: abcdefghjk
      expire: 3